#!/usr/bin/env python3

# Script to create slurm array job files from svsim mock genome (.fa) files. random_reads_template.txt should be in same directory.

# python3 create_slurm_from_fq.py /work/Wasmuth_lab/mrkyle/repos/sv_pipeline/0_create_training_data/bbtools/random_reads_output/deletions 
import fileinput
import argparse
import os

TEMPLATE_FILE="./align_template.txt"

parser = argparse.ArgumentParser()
parser.add_argument("input_dir", help="Parent directory for the simulated genomes (.fa format).")
parser.add_argument("output_dir", help="Directory to export the slurm files to")
args = parser.parse_args()

#FILE_PREFIX
#OUTPUT_DIR
#INPUT_DIR

def create_slurm_script(root, output_path, file_prefix, array_index):
	with open(TEMPLATE_FILE, 'r') as file :
		output_file = args.output_dir +"/" + file_prefix + "." + str(array_index)
		filedata = file.read()
		filedata = filedata.replace('INPUT_DIR', root)
		filedata = filedata.replace('OUTPUT_DIR', output_path)
		filedata = filedata.replace('FILE_PREFIX', file_prefix)

		with open(output_file, 'w') as file:
			file.write(filedata)

# Function determines the variable values that will replace the dummy placeholders in the template file
def create_template_replacements(root, f,array_index):

	output_path = root.replace("0_create_training_data/bbtools/random_reads_output", "2_align_reads/output")
	file_prefix=f.strip("_1.fq")
	#reference_fasta_file = os.path.join(root,f) # NOTE: The reference file is the mock genome .fa file generated by svsim, not the C. elegans reference genome
	#job_prefix=f.split(".fa")[0]
	create_slurm_script(root, output_path, file_prefix, array_index)
	


depth = 2 # Script is intended to be used with subdirectories one directory deep in parent folder
if os.path.isdir(args.input_dir):
	array_index=1
	my_dir = os.path.abspath(os.path.expanduser(os.path.expandvars(args.input_dir)))
	for root,dirs,files in os.walk(my_dir):
		if root[len(my_dir):].count(os.sep) < depth:
			for f in files:
				if f.endswith("1.fq"):
					create_template_replacements(root, f,array_index)
					array_index+=1


