#!/usr/bin/env python3

# Script to create slurm array job files from svsim mock genome (.fa) files. random_reads_template.txt should be in same directory.

# python3 create_slurm_from_bam.py /work/Wasmuth_lab/mrkyle/repos/sv_pipeline/2_align_reads/output/deletions ./deletions
import fileinput
import argparse
import os

TEMPLATE_FILE="./call_variants_template.txt"

parser = argparse.ArgumentParser()
parser.add_argument("input_dir", help="Parent directory for the alignment files (.bam format).")
parser.add_argument("output_dir", help="Directory to export the slurm files to")
args = parser.parse_args()

def create_slurm_script(file_prefix,reference_bam_file,output_path,array_index):
	with open(TEMPLATE_FILE, 'r') as file :
		output_file = args.output_dir +"/" + file_prefix + "." + str(array_index)
		filedata = file.read()
		filedata = filedata.replace('INPUT_DIR', output_path)
		filedata = filedata.replace('OUTPUT_DIR', output_path)
		filedata = filedata.replace('FILE_PREFIX', file_prefix)

		with open(output_file, 'w') as file:
			file.write(filedata)
	

# Function determines the variable values that will replace the dummy placeholders in the template file
def create_template_replacements(root, f,array_index):
	output_path = root.replace("svsim", "bbtools")
	reference_bam_file = os.path.join(root,f) # NOTE: The reference file is the mock genome .fa file generated by svsim, not the C. elegans reference genome
	file_prefix=f.split(".bam")[0]
	create_slurm_script(file_prefix,reference_bam_file,output_path,array_index)


depth = 2 # Script is intended to be used with subdirectories one directory deep in parent folder
if os.path.isdir(args.input_dir):
	array_index=1
	my_dir = os.path.abspath(os.path.expanduser(os.path.expandvars(args.input_dir)))
	for root,dirs,files in os.walk(my_dir):
		if root[len(my_dir):].count(os.sep) < depth:
			for f in files:
				if f.endswith(".bam"):
					if ("discordants" not in f) and ("splitters" not in f):
						create_template_replacements(root, f,array_index)
						array_index+=1
				



